version: 1.0.{build}

# TODO: Add MSVC support
image: Visual Studio 2019

platform: x64

environment:
  matrix:
    - BUILD_SHARED: OFF
      COMPILER: cygwin

for:
  - matrix:
      only:
        - OQS_USE_OPENSSL: OFF
    before_build:
      - cmd: |-
             choco install openssl
             choco install -y strawberryperl
             SET "OPENSSL_ROOT_DIR=C:\OpenSSL-Win64"

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor_build.bat'

before_test:
  - cmd: |-
         SET "PATH=C:\Python37;C:\Python37\Scripts;%PATH%"
         pip.exe install pytest pytest-xdist psutil

test_script:
  - cmd: |-
         cd %APPVEYOR_BUILD_FOLDER%
         echo "%PATH%"
         set PATH=%cd%;c:\cygwin64\bin;%PATH% && echo %PATH% && python oqs-test/try_connection.py doone

