version: 2

.openssh_job: &opensshjob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout
    - run:
        name: Set up SSH environment
        command: |
          mkdir -p -m 0755 /var/empty
          groupadd sshd
          useradd -g sshd -c 'sshd privsep' -d /var/empty -s /bin/false sshd
    - run:
        name: Clone liboqs
        command: cd oqs_test && scripts/clone_liboqs.sh
    - run:
        name: Build liboqs
        command: cd oqs_test && scripts/build_liboqs.sh
    - run:
        name: Build OpenSSH
        command: cd oqs_test && scripts/build_openssh.sh
    - run:
        name: Run unit tests
        command: cd oqs_test && mkdir -p test-results && python3 -m nose --rednose --verbose --with-xunit --xunit-file=test-results/nosetests.xml
    - store_test_results: # Note that this command will fail when running CircleCI locally, that is expected behaviour
        path: oqs_test/test-results

jobs:
  # amd64-buster (Debian 10)
  debian-buster-amd64-with-openssl-with-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:debian-buster-amd64-0.1.0
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: true
  debian-buster-amd64-with-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:debian-buster-amd64-0.1.0
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: false
  debian-buster-amd64-no-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:debian-buster-amd64-0.1.0
      ARCH: x64
      WITH_OPENSSL: false
      WITH_PQAUTH: false
  # x86_64-xenial (Ubuntu 16.04)
  ubuntu-xenial-x86_64-with-openssl-with-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:ubuntu-xenial-x86_64-0.1.0
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: true
  ubuntu-xenial-x86_64-with-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:ubuntu-xenial-x86_64-0.1.0
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: false
  ubuntu-xenial-x86_64-no-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:ubuntu-xenial-x86_64-0.1.0
      ARCH: x64
      WITH_OPENSSL: false
      WITH_PQAUTH: false
      
workflows:
  version: 2
  build:
    jobs:
      - debian-buster-amd64-with-openssl-with-pqauth
      - debian-buster-amd64-with-openssl-no-pqauth
      - debian-buster-amd64-no-openssl-no-pqauth
      - ubuntu-xenial-x86_64-with-openssl-with-pqauth
      - ubuntu-xenial-x86_64-with-openssl-no-pqauth
      - ubuntu-xenial-x86_64-no-openssl-no-pqauth
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: 
                - OQS-master
    jobs:
      - debian-buster-amd64-with-openssl-with-pqauth
      - debian-buster-amd64-with-openssl-no-pqauth
      - debian-buster-amd64-no-openssl-no-pqauth
      - ubuntu-xenial-x86_64-with-openssl-with-pqauth
      - ubuntu-xenial-x86_64-with-openssl-no-pqauth
      - ubuntu-xenial-x86_64-no-openssl-no-pqauth
